export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_GOOGLE_TOKEN_INVALID: 'AUTH_GOOGLE_TOKEN_INVALID',
  AUTH_GOOGLE_ACCOUNT_MISMATCH: 'AUTH_GOOGLE_ACCOUNT_MISMATCH',

  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Business / Listing
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BUSINESS_ACCESS_DENIED: 'BUSINESS_ACCESS_DENIED',
  BUSINESS_INVALID_STATE_TRANSITION: 'BUSINESS_INVALID_STATE_TRANSITION',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  LISTING_INCOMPLETE: 'LISTING_INCOMPLETE',

  // Offers
  OFFER_NOT_FOUND: 'OFFER_NOT_FOUND',
  OFFER_NOT_ALLOWED: 'OFFER_NOT_ALLOWED',
  OFFER_INVALID_STATE_TRANSITION: 'OFFER_INVALID_STATE_TRANSITION',
  OFFER_ALREADY_ACCEPTED: 'OFFER_ALREADY_ACCEPTED',

  // Deals
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  DEAL_ACCESS_DENIED: 'DEAL_ACCESS_DENIED',
  DEAL_INVALID_STATE_TRANSITION: 'DEAL_INVALID_STATE_TRANSITION',

  // Documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',
  DOCUMENT_INVALID_FILE: 'DOCUMENT_INVALID_FILE',

  // Conversations
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ACCESS_DENIED: 'CONVERSATION_ACCESS_DENIED',

  // AI
  AI_ANALYSIS_UNAVAILABLE: 'AI_ANALYSIS_UNAVAILABLE',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_INSUFFICIENT_DATA: 'AI_INSUFFICIENT_DATA',

  // Webhooks
  WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
